### ISSUE TITLE
Got patched.

### ISSUE THREAD

**Issue by DatSkyr3x** [33kk/roblox-stream-sniper#1]
Now it always just says: Something went wrong! Check your input! Error message: Request failed after 10 retries!
Inner Exception: NULL
Didnt manage to fix it. Someone please try to unpatch it so we all can skid :)

**Comment by 33kk** [comment]
I think reason is my shitcode or api rate limits. Ill rewrite it tomorrow if i dont get lazy

**Comment by 33kk** [comment]
I think it should work now.

**Comment by 33kk** [comment]
Closing for now.
