### ISSUE TITLE
cmd closes when opening it

### ISSUE THREAD

**Issue by DatSkyr3x** [33kk/roblox-stream-sniper#2]
so i tried the release and building it myself, i created the dotnet and did everything properly and didnt get any errors at any point, yet the cmd window quickly pops up and instantly closes again when i try opening kk33.RbxStreamSniper.exe. how do i fix this?

**Comment by 33kk** [comment]
Run `cmd` and then `kk33.RbxStreamSniper.exe --help` there. Just like other console apps
